name: horizontal_compass
description: A customizable horizontal compass.
version: 1.0.0
homepage: 'https://darkfox.pl/flutter/horizontal-compass'

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pl.darkfox.horizontal_compass
        pluginClass: HorizontalCompassPlugin
      ios:
        pluginClass: HorizontalCompassPlugin
      linux:
        pluginClass: HorizontalCompassPlugin
      macos:
        pluginClass: HorizontalCompassPlugin
      windows:
        pluginClass: HorizontalCompassPluginCApi
      web:
        pluginClass: HorizontalCompassWeb
        fileName: horizontal_compass_web.dart
